use fluxocaixa;

create login escolateste with password = '1234';
create user escolateste with default_schema = dbo;

GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.T_CLSSF_PLANO_CONTA TO  escolateste; 
GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.T_CNRIO_IMPRT_ARQV TO  escolateste; 
GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.T_CNRO_EXPRT_ARQV TO  escolateste;
GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.T_FLUXO_CAIXA TO  escolateste;
GRANT SELECT, UPDATE, DELETE, INSERT ON dbo.T_LISTA_PLVR_EXCD TO  escolateste;

GRANT SELECT ON dbo.T_DMSAO_TEMPO TO  escolateste; 

GRANT ALTER, UPDATE ON dbo.SQ_CLSSF_PLANO_CONTA TO  escolateste; 
GRANT ALTER, UPDATE ON dbo.SQ_CNRIO_EXPRT_ARQV TO  escolateste; 
GRANT ALTER, UPDATE ON dbo.SQ_CNRIO_IMPRT_ARQV TO  escolateste;
GRANT ALTER, UPDATE ON dbo.SQ_FLUXO_CAIXA TO  escolateste;
GRANT ALTER, UPDATE ON dbo.SQ_LISTA_PLVR_EXCD TO  escolateste;

GRANT SELECT ON dbo.VW_FLUXO_CAIXA_POR_DS_MES TO  escolateste; 
GRANT SELECT ON dbo.VW_TRIM_SAIDA_CAIXA TO  escolateste; 
