CREATE TABLE fluxocaixa.dbo.T_DMSAO_TEMPO (
	ID_DMSAO_TEMPO int NOT NULL,
	DT_DMSAO_TEMPO date NOT NULL,
	NU_DIA_MVMT_FLUXO_CAIXA int NOT NULL,
	NU_MES_MVMT_FLUXO_CAIXA int NOT NULL,
	NU_ANO_MVMT_FLUXO_CAIXA int NOT NULL,
	DS_MES_FLUXO_CAIXA varchar(50),
	DS_BMST_MVMT_FLUXO_CAIXA varchar(50) NOT NULL,
	DS_TRMT_MVMT_FLUXO_CAIXA varchar(50) NOT NULL,
	DS_SMST_MVMT_FLUXO_CAIXA varchar(50) NOT NULL,
	PRIMARY KEY (ID_DMSAO_TEMPO)
)	
CREATE TABLE fluxocaixa.dbo.T_FLUXO_CAIXA (
	ID_FLUXO_CAIXA int NOT NULL,
	NU_CNPJ varchar(18) NOT NULL,
	SK_DMSAO_TEMPO int NOT NULL,
	DT_MVMT_FLUXO_CAIXA date NOT NULL,
	DS_CLSSF_PLANO_CONTA varchar(100) NOT NULL,
	CD_DCTO_RFRC_FLUXO_CAIXA varchar(20) NOT NULL,
	CD_PLANO_CONTA varchar(10) NOT NULL,
	DS_PLANO_CONTA varchar(100) NOT NULL,
	DS_INSTT_FNCR varchar(50) NOT NULL,
	VL_ENTR_FLUXO_CAIXA decimal(11,2),
	VL_SAIDA_FLUXO_CAIXA decimal(11,2),
	IC_STATUS_VALOR varchar(20) NOT NULL,
	NM_CLIE_FLUXO_CAIXA varchar(200),
	PRIMARY KEY (ID_FLUXO_CAIXA)
)	
ALTER TABLE fluxocaixa.dbo.T_FLUXO_CAIXA
	ADD FOREIGN KEY (SK_DMSAO_TEMPO) 
	REFERENCES dbo.T_DMSAO_TEMPO (ID_DMSAO_TEMPO)	


CREATE VIEW VW_TRIM_SAIDA_CAIXA AS
SELECT FLUXO.DS_CLSSF_PLANO_CONTA
     , FLUXO.DS_PLANO_CONTA
     , DMSAO.DS_TRMT_MVMT_FLUXO_CAIXA
     , DMSAO.DS_MES_FLUXO_CAIXA
     , DMSAO.NU_ANO_MVMT_FLUXO_CAIXA
     , FLUXO.DT_MVMT_FLUXO_CAIXA
     , FLUXO.VL_SAIDA_FLUXO_CAIXA
FROM T_FLUXO_CAIXA FLUXO
   , T_DMSAO_TEMPO DMSAO
WHERE FLUXO.SK_DMSAO_TEMPO = DMSAO.ID_DMSAO_TEMPO
  AND FLUXO.DS_CLSSF_PLANO_CONTA IN ('DESPESAS OPERACIONAIS', 'DESPESAS COM RH');
