USE FLUXOCAIXA;
DROP VIEW VW_FLUXO_CAIXA_POR_DS_MES;

CREATE VIEW VW_FLUXO_CAIXA_POR_DS_MES AS 
SELECT CONVERT(nchar,DT_MVMT_FLUXO_CAIXA, 103) "DATA DE MOVIMENTACAO"
     , FLUXO.DS_CLSSF_PLANO_CONTA "CLASSIFICACAO PLANO DE CONTA"
     , FLUXO.CD_PLANO_CONTA "CODIGO DO PLANO DE CONTA"
     , FLUXO.DS_PLANO_CONTA "DESCRICAO DO PLANO DE CONTA"
	 , FLUXO.CD_DCTO_RFRC_FLUXO_CAIXA "DOC DE REF"
	 , TEMPO.DS_MES_FLUXO_CAIXA "MES DO FLUXO DE CAIXA"
	 , CONVERT(nchar, TEMPO.NU_ANO_MVMT_FLUXO_CAIXA) "ANO DO FLUXO DE CAIXA"
	 , FLUXO.DS_INSTT_FNCR "INSTITUICAO FINANCEIRA"
	 , FLUXO.VL_ENTR_FLUXO_CAIXA "VALOR DE ENTRADA"
	 , FLUXO.VL_SAIDA_FLUXO_CAIXA "VALOR DE SAIDA"
	 , FLUXO.IC_STATUS_VALOR "STATUS DO FLUXO DE CAIXA"
	 , FLUXO.NU_CNPJ "CNPJ"
FROM dbo.T_FLUXO_CAIXA FLUXO
   , dbo.T_DMSAO_TEMPO TEMPO
WHERE FLUXO.SK_DMSAO_TEMPO = TEMPO.ID_DMSAO_TEMPO;
